### ISSUE TITLE
Local storage is sending a file update message to files that does not exist

### ISSUE THREAD

**Issue by rodrigopavezi** [Rise-Vision/local-storage-module#69]
When looking at the Twitter Module logs we see that it is getting a file update message from loca storage for a file that does not exist on GCS.

<img width="1113" alt="screen shot 2018-04-12 at 16 47 12" src="https://user-images.githubusercontent.com/1659305/38700398-490a6850-3e71-11e8-95e7-72a173a7593e.png">

BQ: https://bigquery.cloud.google.com/results/client-side-events:US.bquijob_2ef5d471_162bb59f8ed

That is the case where a company hasn't setup twitter credentials but a Twitter Module sets the watch for it.

I think it is happening every time the Twitter Module starts.

How it should work?

Local Storage should not send a FILE_UPDATE message on this case where there is no file on GCS for it.

Cheers

**Comment by alanclayton** [comment]
@tejohnso @stulees should this be a defect on our board?

**Comment by alanclayton** [comment]
@stulees 👍

**Comment by andrecardoso** [comment]
@rodrigopavezi @stulees this is not an issue. It happens because twitter-module try to read the file when its status is "STALE" and it doesn't exist in the disk yet. We need to fix by adding a `platform.fileExists(credentialsPath)` check [here](https://github.com/Rise-Vision/twitter-module/blob/master/src/messaging/watch/watch.js#L64) the same as in [display-control](https://github.com/Rise-Vision/display-control-module/blob/master/src/watch.js#L52) and [licensing](https://github.com/Rise-Vision/licensing-module/blob/master/src/watch.js#L141). I think we can close this issue.

**Comment by sheadarlison** [comment]
@rodrigopavezi Should we make this change as part of your current card?

**Comment by stulees** [comment]
@andrecardoso Thanks! @sheadarlison @rodrigopavezi This issue should be moved to Twitter module. @alanclayton FYI

**Comment by rodrigopavezi** [comment]
@sheadarlison someone disabled issues on this repo. I enabled it again. so now we can see it. Sure, I will make the change as part of the card I am working on. Cheers

**Comment by sheadarlison** [comment]
Thanks! @rodrigopavezi

**Comment by rodrigopavezi** [comment]
@andrecardoso has clarified me why it needs to be checked in the module. cheers
